patterns = [
    [{"LOWER": "this"}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["calling", "speaking"]}}],
    [{"LOWER": {"IN": ["i", "i'm", "my"]}}, {"LOWER": "name"}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["here", "speaking", "calling"]}}],
    [{"LOWER": "you're"}, {"LOWER": "speaking"}, {"LOWER": {"IN": ["with", "to"]}}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["hello", "hi", "hey"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["i", "i'm"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["calling", "speaking"]}}],
    [{"LOWER": {"IN": ["hello", "hi", "hey"]}}, {"LOWER": "there"}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["good", "hello"]}}, {"LOWER": {"IN": ["morning", "afternoon", "evening"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["speaking", "here"]}}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": "you've"}, {"LOWER": "reached"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["i'm", "i", "this", "it's"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": {"IN": ["hello", "hi"]}}, {"LOWER": {"IN": ["you're", "you", "i'm"]}}, {"LOWER": "through"}, {"LOWER": "to"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "on"}, {"LOWER": "the"}, {"LOWER": "line"}],
    [{"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["speaking", "here"]}}, {"LOWER": "how"}, {"LOWER": "can"}, {"LOWER": "i"}, {"LOWER": "help"}],
    [{"LOWER": {"IN": ["you're", "you", "i'm"]}}, {"LOWER": "speaking"}, {"LOWER": "with"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"POS": "ADP"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": {"IN": ["i'm", "i", "this", "it's"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["calling", "speaking"]}}, {"LOWER": "on"}, {"LOWER": "behalf"}, {"LOWER": "of"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": {"IN": ["hello", "hi", "greetings"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["calling", "speaking"]}}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["i'm", "i", "this", "it's"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "with"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["here", "speaking", "calling"]}}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["hello", "hi", "hey"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"TITLE": {"IN": ["dr", "professor", "mr", "ms", "mrs"]}}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["i'm", "i", "this", "it's"]}}, {"TITLE": {"IN": ["dr", "professor", "mr", "ms", "mrs"]}}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["hello", "hi", "hey"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["i'm", "i", "this", "it's"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["the", "your"]}}, {"LOWER": {"IN": ["new", "current", "assigned"]}}, {"LOWER": {"IN": ["representative", "agent", "consultant"]}}],
    [{"LOWER": {"IN": ["you're", "you", "i'm"]}}, {"LOWER": "connected"}, {"LOWER": "to"}, {"POS": "PROPN", "OP": "+"}],
]