patterns = [
    [{"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["calling", "speaking"]}}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["in", "at"]}}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "based"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"ENT_TYPE": "GPE"}, {"LOWER": "office"}],
    [{"LOWER": "office"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "currently"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "located"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "here"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "calling"}, {"LOWER": "you"}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "reaching"}, {"LOWER": "out"}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "on"}, {"LOWER": "the"}, {"LOWER": "line"}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "speaking"}, {"LOWER": "to"}, {"LOWER": "you"}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["i'm", "i", "we're", "we"]}}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}, {"LOWER": "right"}, {"LOWER": "now"}],
    [{"LOWER": {"IN": ["i'm", "i"]}}, {"LOWER": "calling"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "at"}, {"LOWER": "our"}, {"LOWER": {"IN": ["office", "headquarters", "branch"]}}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["visiting", "traveling"]}}, {"ENT_TYPE": "GPE"}, {"LOWER": "at"}, {"LOWER": "the"}, {"LOWER": "moment"}],
    [{"LOWER": "on"}, {"LOWER": "business"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "working"}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}, {"LOWER": "today"}],
    [{"LOWER": "attending"}, {"LOWER": "a"}, {"LOWER": {"IN": ["conference", "meeting", "event"]}}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "currently"}, {"LOWER": "stationed"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "temporarily"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": "calling"}, {"LOWER": "from"}, {"LOWER": "the"}, {"ENT_TYPE": "GPE"}, {"LOWER": {"IN": ["office", "branch", "headquarters"]}}],
    [{"LOWER": "in"}, {"LOWER": "the"}, {"ENT_TYPE": "GPE"}, {"LOWER": "area"}],
    [{"LOWER": "out"}, {"LOWER": "of"}, {"LOWER": "our"}, {"ENT_TYPE": "GPE"}, {"LOWER": "location"}],
    [{"LOWER": {"IN": ["stationed", "posted", "assigned"]}}, {"LOWER": "to"}, {"LOWER": "our"}, {"ENT_TYPE": "GPE"}, {"LOWER": {"IN": ["office", "branch", "unit"]}}],
]