patterns = [
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["hello", "hi", "hey"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"POS": "PROPN", "OP": "+"}, {"LOWER": "speaking"}],
    [{"LOWER": {"IN": ["you're", "you", "i'm"]}}, {"LOWER": "speaking"}, {"LOWER": "with"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["how", "what"]}, "OP": "?"}, {"LOWER": "can"}, {"LOWER": "i"}, {"LOWER": {"IN": ["help", "assist", "do"]}, "OP": "?"}],
    [{"LOWER": {"IN": ["yes", "hello", "hi"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"TITLE": {"IN": ["dr", "professor", "mr", "ms", "mrs"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "speaking"}],
    [{"LOWER": {"IN": ["you've", "you", "i've"]}}, {"LOWER": "reached"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["hello", "hi", "yes"]}}, {"LOWER": {"IN": ["you're", "you", "i'm"]}}, {"LOWER": "through"}, {"LOWER": "to"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": {"IN": ["i'm", "this", "it's"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": {"IN": ["good", "hello"]}}, {"LOWER": {"IN": ["morning", "afternoon", "evening"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["you're", "you", "i'm"]}}, {"LOWER": "connected"}, {"LOWER": "to"}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "on"}, {"LOWER": "the"}, {"LOWER": "line"}],
    [{"LOWER": {"IN": ["yes", "hello", "hi"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"TITLE": {"IN": ["dr", "professor", "mr", "ms", "mrs"]}}, {"POS": "PROPN", "OP": "+"}],
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["speaking", "here"]}}, {"LOWER": "from"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["hello", "hi", "yes"]}}, {"LOWER": {"IN": ["this", "i'm"]}}, {"POS": "PROPN", "OP": "+"}, {"LOWER": {"IN": ["speaking", "here"]}}, {"LOWER": "how"}, {"LOWER": "can"}, {"LOWER": "i"}, {"LOWER": "help"}],
    [{"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "of"}, {"ENT_TYPE": "ORG", "OP": "+"}],
    [{"LOWER": {"IN": ["yes", "hello", "hi"]}}, {"LOWER": {"IN": ["this", "it"]}}, {"LOWER": "is"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}, {"LOWER": "in"}, {"ENT_TYPE": "GPE"}],
    [{"LOWER": {"IN": ["you're", "you", "i'm"]}}, {"LOWER": "speaking"}, {"LOWER": "with"}, {"POS": "PROPN", "OP": "+"}, {"LOWER": "from"}, {"ENT_TYPE": "ORG", "OP": "+"}],
]