from domain.ai.embeddings.transformer.transformer_embeddings import TransformerEmbeddings
from domain.ai.keywords.transformer.transformer_keywords_extractor import TransformerKeywordsExtractor
from domain.ai.speech_recognition.whisper.whisper_speech_recognizer import WhisperSpeechRecognizer
from domain.features.call_analysis.category_classification.vector_based.vector_based_call_category_classifier import VectorBasedCallCategoryClassifier
from domain.features.call_analysis.emotional_tone.transformer_call_emotional_tone_analyzer import TransformerCallEmotionalToneAnalyzer
from domain.features.call_analysis.entities_extraction.rule_based.rule_based_call_entities_extractor import RuleBasedCallEntitiesExtractor
from domain.features.call_analysis.transcription.call_downloader import CallDownloader, CallDownloaderConfig
from domain.features.call_analysis.transcription.call_transcriber import CallTranscriber
from infrastructure.repositories.mongo_analysis_result_repository import MongoAnalysisResultRepository
from infrastructure.repositories.mongo_analysis_state_repository import MongoAnalysisStateRepository
from infrastructure.vectorstores.weaviate_call_keywords_vector_store import WeaviateCallKeywordsVectorStore
from infrastructure.vectorstores.weaviate_category_vector_store import WeaviateCategoryVectorStore


analysis_state_repository = MongoAnalysisStateRepository()
analysis_result_repository = MongoAnalysisResultRepository()

speech_recognizer = WhisperSpeechRecognizer()
call_downloader=CallDownloader(CallDownloaderConfig.TMP_FOLDER)
transcriber = CallTranscriber(speech_recognizer, call_downloader)

emotional_tone_analyzer = TransformerCallEmotionalToneAnalyzer()

entities_extractor = RuleBasedCallEntitiesExtractor()

keywords_extractor = TransformerKeywordsExtractor()
embeddings = TransformerEmbeddings()
keywords_store = WeaviateCallKeywordsVectorStore(embeddings)
category_store = WeaviateCategoryVectorStore(embeddings)
category_classifier = VectorBasedCallCategoryClassifier(keywords_extractor, keywords_store, category_store)
